name: Install K3s on EC2

on:
  workflow_dispatch:

jobs:
  install_k3s:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml